# Generated by Django 5.1.15 on 2026-03-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=30)),
                ('subject_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Assigned, not started)'), ('DRAFT', 'Draft (In Progress)'), ('SUBMITTED', 'Submitted to HOD'), ('UNDER_REVIEW', 'Under HOD Review'), ('REVISION', 'Revision Requested'), ('APPROVED', 'Approved by HOD'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('lecture_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tutorial_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('practical_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('studio_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('independent_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pre_requisite', models.CharField(blank=True, max_length=300)),
                ('co_requisite', models.CharField(blank=True, max_length=300)),
                ('course_description', models.TextField(blank=True)),
                ('sdg_justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_document_generated', models.DateTimeField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/syllabi/')),
                ('assigned_faculty', models.ForeignKey(blank=True, limit_choices_to={'role': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL)),
                ('created_by_hod', models.ForeignKey(limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
                ('curriculum_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.curriculumversion')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.department')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SMEDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sme_detail', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SDGMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sdg_number', models.CharField(max_length=10)),
                ('sdg_theme', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_mappings', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('citation', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicals', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticulationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po1', models.IntegerField(blank=True, null=True)),
                ('po2', models.IntegerField(blank=True, null=True)),
                ('po3', models.IntegerField(blank=True, null=True)),
                ('po4', models.IntegerField(blank=True, null=True)),
                ('po5', models.IntegerField(blank=True, null=True)),
                ('po6', models.IntegerField(blank=True, null=True)),
                ('po7', models.IntegerField(blank=True, null=True)),
                ('po8', models.IntegerField(blank=True, null=True)),
                ('po9', models.IntegerField(blank=True, null=True)),
                ('po10', models.IntegerField(blank=True, null=True)),
                ('po11', models.IntegerField(blank=True, null=True)),
                ('pso1', models.IntegerField(blank=True, null=True)),
                ('pso2', models.IntegerField(blank=True, null=True)),
                ('co', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_row', to='subjects.courseoutcome')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulation_rows', to='subjects.subject')),
            ],
            options={
                'ordering': ['co__order'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('citation', models.TextField()),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='subjects.subject')),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status', 'department'], name='subjects_su_status_c4d45e_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['assigned_faculty', 'status'], name='subjects_su_assigne_c71c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'curriculum_version')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('subject', 'unit_number')},
        ),
    ]
