# Generated by Django 5.1.15 on 2026-03-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campus_campusschool_campusschooldepartment_school_and_more'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Type',
                'verbose_name_plural': 'Course Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=50)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('lecture_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tutorial_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('practical_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('studio_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('independent_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pre_requisite', models.CharField(blank=True, max_length=500)),
                ('co_requisite', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('campus_school_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.campusschooldepartment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_modified', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='subjects.coursecategory')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='subjects.coursetype')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField()),
                ('unit_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='subjects.course')),
            ],
            options={
                'verbose_name': 'Course Unit',
                'verbose_name_plural': 'Course Units',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.PositiveIntegerField()),
                ('topic_title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.courseunit')),
            ],
            options={
                'verbose_name': 'Course Topic',
                'verbose_name_plural': 'Course Topics',
                'ordering': ['topic_number'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='subjects_co_course__31b5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='subjects_co_is_acti_caf1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['campus_school_department', 'is_active'], name='subjects_co_campus__7d2dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_active'], name='subjects_co_categor_d98435_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'campus_school_department')},
        ),
        migrations.AddIndex(
            model_name='courseunit',
            index=models.Index(fields=['course', 'is_active'], name='subjects_co_course__ce70a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseunit',
            unique_together={('course', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='coursetopic',
            index=models.Index(fields=['unit', 'is_active'], name='subjects_co_unit_id_25b917_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetopic',
            unique_together={('unit', 'topic_number')},
        ),
    ]
