# Generated by Django 5.1.15 on 2026-03-10 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampusSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus-School Mapping',
                'verbose_name_plural': 'Campus-School Mappings',
                'ordering': ['campus', 'school'],
            },
        ),
        migrations.CreateModel(
            name='CampusSchoolDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus-School-Department Mapping',
                'verbose_name_plural': 'Campus-School-Department Mappings',
                'ordering': ['campus', 'school', 'department'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='core_depart_code_5a5745_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['status'], name='core_depart_status_5443ac_idx'),
        ),
        migrations.AddField(
            model_name='campus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campus',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusschool',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_mappings', to='core.campus'),
        ),
        migrations.AddField(
            model_name='campusschooldepartment',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_department_mappings', to='core.campus'),
        ),
        migrations.AddField(
            model_name='campusschooldepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_school_mappings', to='core.department'),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campusschooldepartment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_mappings', to='core.school'),
        ),
        migrations.AddField(
            model_name='campusschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_mappings', to='core.school'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['campus_code'], name='core_campus_campus__8cc928_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['is_active'], name='core_campus_is_acti_199728_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_code'], name='core_school_school__c85006_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='core_school_is_acti_2e0f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='campusschooldepartment',
            index=models.Index(fields=['campus', 'is_active'], name='core_campus_campus__d547c0_idx'),
        ),
        migrations.AddIndex(
            model_name='campusschooldepartment',
            index=models.Index(fields=['school', 'is_active'], name='core_campus_school__666bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='campusschooldepartment',
            index=models.Index(fields=['department', 'is_active'], name='core_campus_departm_2eb520_idx'),
        ),
        migrations.AddIndex(
            model_name='campusschooldepartment',
            index=models.Index(fields=['campus', 'school', 'is_active'], name='core_campus_campus__28d2b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campusschooldepartment',
            unique_together={('campus', 'school', 'department')},
        ),
        migrations.AddIndex(
            model_name='campusschool',
            index=models.Index(fields=['campus', 'is_active'], name='core_campus_campus__579d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='campusschool',
            index=models.Index(fields=['school', 'is_active'], name='core_campus_school__1b1998_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campusschool',
            unique_together={('campus', 'school')},
        ),
    ]
